language: node_js

deploy:
  provider: s3
  access_key_id: AKIAI6LDSPCCVC23XKKA
  secret_access_key:
    secure: WbNDvSvMrE9TBIJ/8C6u5tHntqbPD7PuZdnxSJG8/vRyQ70N/YuUjbDr2JQr3cdULxfQSS33q//XlCheWnP+VDVkee2WveyPR2MFYPGRevAgq+4sWmraY8X1I3AysktC+KCGBVH2fmr+atBz+BwKsBRb3UKpHpmnNinvVHXTpJBv7KeLrGip/5gLt5U6ieSlqudsCVSHLANVYOnAtdYPZzbA3mJc/iMrD4j4QzHx3RzCK+lTHkjR8cKvStXCyvC42+NrxzxjMhFyx8yh5+x0TqftKoiNbUu+LNucYdd2hhbOGxuglxiEtAj/iXhqanA4bWTVVNcmAB91/xoZb1w4dPLZ3j9L5UjwncuF+KcIba+oTrylk55Ixdg+O5HBrnjBFjGi5U5kspixNIqwapoJxX23OafrghZwtHosTRLmiN/ISNALy5fbpvKYC6Wass+XsrFXzKylYfBhassVxM/KoDUufewwP8dLbhbJPTZnVO30BFg6tvwYTUPoifdgaHiGDtJn1LlN3kQmRU77xmMS0LVo1RCP0oqDKHR/wKApxtbfcL0TI4qUWxAnLaKHbqM/78+1T86teVws8NQy4N+ON1tSUHUJEcdP2VccwKZGYQITryoDE+6EDrzRRcznny03stMrDOc9v7pvaRJzxNAkjMy6mEgvLPjQiJo+BDgKGU4=
  bucket: japhet.in
  acl: public_read
  on:
    repo: JAnderton/japhet-family-website
