language: node_js
before_deploy: rm -rf .git .gitignore .travis.yml LICENSE README.md
deploy:
  provider: s3
  access_key_id: AKIAILCFX2SMJQBHYXNA
  secret_access_key:
    secure: nl3/Bt7GphUpJhw/zhPukUQ2J3k5C5S/kVpb0S7QGqpAGSQX5X8+f/mNiKczEALZ+ubO7iTdAb+gNUwyMNHYgIdZqPZ8yA60hnDnF2xyQg1cfjj2P8Luwusgb+wKZX0utPgwJ1iSErwsfpyGG0sVVoRzerZjZQxVUdJZxJV34WjfXK6UuvbZa++Cr1n9vwzMs1W7KoYly8qJCVwFC7sUNGwz8tagd1GXCXyTrgnoP3CJgfKkVM51PLXAG6Ub80VGaevS2a0qRE6MWEmsxxVWlP0ziHQzQPw3Z82+5y6rYXEQOsOXGNgPRP2K0Hjtwnlwye8FDPZ/BjhHpc0C7xmxpmzWd2KdZxgwFTiyMoWYhpWux+ho9dxQl3yZ3+IWggAem2ZcF9NeF2f25jwSbQAZuOtEZgG7EijnX4y/IdOGmupZ0D3W0tpNIY4E8SQq65ii9c9wYzOR3kh/PIxJcTojqfDBzSJGU1xxWg7395FyJsOf0FW0QguU3ucofCEftblhaGK8TqhNSeWkxDA/AWHhfkv8KyImu0aNzFjIVfL8DQ0aZyngVT3sQUckUpQLpdzZg1IPqGBp3iZvFBmP3wulplmu0n/LTSPisTEDZzu1Yu1I4yINX1uG4+brUlDIZ3Cu/4MMUydi8sSC7BZF/9Q+syhd8x2xI87UFqUwT2Yq8BM=
  bucket: japhet.in
  acl: public_read
  on:
    repo: JAnderton/japhet-family-website
